### ISSUE TITLE
Repeating CSS styles

### ISSUE THREAD

**Issue by jim-rosales** [erupsyte/prj-rev-bwfs-dasmoto#4]
When writing your CSS rules if you ever find yourself copying and pasting or writing the same styles to different rule sets it usually an indicator that you can find a better approach.

For example, in the following three rule sets you repeat the following styles in all of them:

```CSS
  color: white;
  font-size: 32px;
  font-weight: bold;
```

The only thing that changes between three rule sets is the unique background color they have.

Instead, the best approach would have been to make use of CSS inheritance and apply the styles all the headers use to the `h2` element:

For example:
```CSS
h2 {
  color: white;
  font-size: 32px;
  font-weight: bold;
}

.brushes {
  background-color:mediumspringgreen;
}

.frames {
  background-color:lightcoral;
}

.paint {
  background-color:skyblue;
}
```

This way you only need to apply the unique color and each section inheritance all the styles needed from the h2 element. 

https://github.com/erupsyte/prj-rev-bwfs-dasmoto/blob/dc72a2e0932f780d173bd05df73f419af7ff1593/Dasmotos/resources/index.css#L19-L38
